#!/usr/bin/env python3
"""Convert a Lucide-style stroke SVG (or any single-color <path>/<circle> SVG)
into an Android VectorDrawable XML.

This is the "import a new icon" step referenced in
app/src/main/kotlin/com/franm/gastosmama/data/icons/CategoryIcons.kt — see
that file's header comment for the full three-step workflow.

Usage:
    python3 tools/svg_to_vector.py <icon.svg> <name>
    python3 tools/svg_to_vector.py https://unpkg.com/lucide-static@latest/icons/wallet.svg wallet

Writes app/src/main/res/drawable/ic_cat_<name>.xml. Handles <path> and
<circle> elements with a single stroke color (fill="none"), which covers
every Lucide icon. Anything fancier (gradients, multi-color fills) needs a
hand-written vector drawable instead.
"""
import re
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "app" / "src" / "main" / "res" / "drawable"


def circle_to_path(cx: float, cy: float, r: float) -> str:
    # Two semicircle arcs, matching how vector drawables express a full circle.
    return (
        f"M{cx - r},{cy} "
        f"a{r},{r} 0 1,0 {2 * r},0 "
        f"a{r},{r} 0 1,0 {-2 * r},0"
    )


def convert(svg_text: str) -> tuple[str, list[str]]:
    vb = re.search(r'viewBox="0 0 (\d+(?:\.\d+)?) (\d+(?:\.\d+)?)"', svg_text)
    w, h = (vb.group(1), vb.group(2)) if vb else ("24", "24")

    sw_match = re.search(r'stroke-width="([\d.]+)"', svg_text)
    stroke_width = sw_match.group(1) if sw_match else "2"

    paths = [m.group(1) for m in re.finditer(r'<path\s+d="([^"]+)"', svg_text)]
    for m in re.finditer(
        r'<circle\s+cx="([\d.]+)"\s+cy="([\d.]+)"\s+r="([\d.]+)"', svg_text
    ):
        cx, cy, r = (float(x) for x in m.groups())
        paths.append(circle_to_path(cx, cy, r))

    if not paths:
        raise ValueError("No <path> or <circle> elements found — see this script's docstring")

    return w, h, stroke_width, paths  # type: ignore[return-value]


def to_vector_drawable(w: str, h: str, stroke_width: str, paths: list[str]) -> str:
    path_tags = "\n".join(
        f'    <path\n'
        f'        android:pathData="{d}"\n'
        f'        android:strokeColor="#FF201E1D"\n'
        f'        android:strokeWidth="{stroke_width}"\n'
        f'        android:strokeLineCap="round"\n'
        f'        android:strokeLineJoin="round"\n'
        f'        android:fillColor="@android:color/transparent" />'
        for d in paths
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tools/svg_to_vector.py — stroke color is a placeholder,\n'
        '     overridden at draw time via Icon(tint = ...). -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="24dp"\n'
        f'    android:height="24dp"\n'
        f'    android:viewportWidth="{w}"\n'
        f'    android:viewportHeight="{h}">\n'
        f"{path_tags}\n"
        "</vector>\n"
    )


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    source, name = sys.argv[1], sys.argv[2]

    if source.startswith("http://") or source.startswith("https://"):
        with urllib.request.urlopen(source, timeout=15) as resp:
            svg_text = resp.read().decode("utf-8")
    else:
        svg_text = Path(source).read_text(encoding="utf-8")

    w, h, stroke_width, paths = convert(svg_text)
    out = to_vector_drawable(w, h, stroke_width, paths)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / f"ic_cat_{name}.xml"
    out_path.write_text(out, encoding="utf-8")
    print(f"Wrote {out_path.relative_to(REPO_ROOT)}")
    print(
        f"Next: add an entry to CATEGORY_ICONS in CategoryIcons.kt, e.g.\n"
        f'    "Nueva categoría" to R.drawable.ic_cat_{name},'
    )


if __name__ == "__main__":
    main()
